// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "evadcmd",
            "email": "evadcmd@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v0/mrkl": {
            "post": {
                "description": "a MRKL API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/api/v0"
                ],
                "summary": "k8s readiness probe",
                "parameters": [
                    {
                        "description": "Q",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Q"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "a readiness probe for k8s",
                "tags": [
                    "healthcheck"
                ],
                "summary": "k8s readiness probe",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Q": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "hi"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:5252",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "RaBOT",
	Description:      "an experimental chat API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
